[package]
name = "my_no_sql_server"
version = "0.0.3"
authors = ["amigin <amigin@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
my-azure-storage-sdk = { branch = "main", git = "https://github.com/MyJetTools/my-azure-storage.git" }
flurl = { branch = "main", git = "https://github.com/MyJetTools/fl-url" }
my-no-sql-tcp-shared = { branch = "main", git = "https://github.com/MyJetTools/my-no-sql-tcp-shared.git" }
rust-extensions = { branch = "main", git = "https://github.com/MyJetTools/rust-extensions.git" }
my-http-utils = { branch = "main", git = "https://github.com/MyJetTools/my-http-utils.git" }
my-telemetry = { branch = "main", git = "https://github.com/MyJetTools/my-telemetry.git" }
my-app-insights = { branch = "main", git = "https://github.com/MyJetTools/my-app-insights.git" }


hyper-tls = "0.5.0"
tonic = { version = "0.5.0", features = ["tls", "tls-roots", "prost"] }
anyhow = "1.0.40"
tokio = { version = "1.5.0", features = ["full"] }
hyper = { version = "0.14", features = ["full"] }
prost = "0.8.0"
serde = { version = "*", features = ["derive"] }
tokio-util = "*"
futures = "*"
chrono = "0.4.19"
futures-util = { version = "0.3", default-features = false }
futures-core = { version = "0.3", default-features = false }
futures-channel = "0.3"
serde_json = "1.0"
serde_derive = "1.0"
quick-xml = "*"
lazy_static = "*"
hmac = "*"
sha2 = "*"
base64 = "*"
serde_yaml = "*"
uuid = { version = "*", features = ["serde", "v4"] }
prometheus = "*"
signal-hook = "*"
async-trait = "*"
tokio-stream = "*"
appinsights = "*"

[build-dependencies]
tonic-build = { version = "0.5.0", features = ["prost"] }
