[package]
name = "my_no_sql_server"
version = "0.0.4"
authors = ["amigin <amigin@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
my-azure-storage-sdk = { branch = "main", git = "https://github.com/MyJetTools/my-azure-storage.git" }
flurl = { branch = "main", git = "https://github.com/MyJetTools/fl-url" }
my-no-sql-tcp-shared = { branch = "main", git = "https://github.com/MyJetTools/my-no-sql-tcp-shared.git" }
rust-extensions = { branch = "main", git = "https://github.com/MyJetTools/rust-extensions.git" }
my-telemetry = { branch = "main", git = "https://github.com/MyJetTools/my-telemetry.git" }
my-app-insights = { branch = "main", git = "https://github.com/MyJetTools/my-app-insights.git" }
my-http-server = { branch = "0.1.1", git = "https://github.com/MyJetTools/my-http-server.git" }

hyper-tls = "*"
tonic = { version = "*", features = ["tls", "tls-roots", "prost"] }
anyhow = "*"
tokio = { version = "*", features = ["full"] }
hyper = { version = "*", features = ["full"] }
prost = "*"
serde = { version = "*", features = ["derive"] }
tokio-util = "*"
futures = "*"
chrono = "*"
futures-util = { version = "*", default-features = false }
futures-core = { version = "*", default-features = false }
futures-channel = "*"
serde_json = "*"
serde_derive = "*"
quick-xml = "*"
lazy_static = "*"
hmac = "*"
sha2 = "*"
base64 = "*"
serde_yaml = "*"
uuid = { version = "*", features = ["serde", "v4"] }
prometheus = "*"
signal-hook = "*"
async-trait = "*"
tokio-stream = "*"
appinsights = "*"
my-http-macros = { path = "./my-http-macros" }

[build-dependencies]
tonic-build = { version = "*", features = ["prost"] }
