mod delete_partition;
//TODO - thing about this usecase;
//mod delete_table;
mod save_partition;
mod save_table;
mod save_table_attributes;
pub use delete_partition::delete_partition;
//pub use delete_table::delete_table;
pub use save_partition::save_partition;
pub use save_table::save_table;
pub use save_table_attributes::save_table_attributes;
