name: Test it

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  PROJECT_DIR: my-no-sql-server

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install Protoc
        uses: arduino/setup-protoc@v1            

      - name: Test Build      
        run: |
          cd ${PROJECT_DIR}
          cargo test